feat: update device
ToDoTurtle/ToDoTurtle pull request #57
Opened 2023-03-07 09:19 UTC by oriolagobat

Closes #48

2023-03-07 11:34 UTC, FerranAD approved these changes

2023-03-07 14:34 UTC, Pablito2020 requested changes
The next time, is MANDATORY to do only one refactor/feature for pull request, if it doesn't follow the standards accorded on #43 , it will be closed immediately.

And please, be aware to test the use case, not the value object implementations

2023-03-07 14:34 UTC, Pablito2020 commented on src/test/kotlin/device/application/DeviceCreatorTest.kt
> +            Identifier(invalidIdPrimitive)
This should test the use case, not the identifier implementation

2023-03-07 14:34 UTC, Pablito2020 commented on src/test/kotlin/shared/mothers/IdentifierMother.kt
> +    fun getInvalidIdentifierPrimitive() = invalidPrimitiveIdentifier
Not needed, you can access it via the constant (invalidPrimitiveIdentifier), a funtion isn't really needed

2023-03-07 14:34 UTC, Pablito2020 commented on src/test/kotlin/device/mothers/DeviceMother.kt
> +    fun getDeviceWithDifferentNameFrom(device: Device) = device.copy(
The copy isn't really needed if you change all the fields (like you are doing here). If you change all the fields a new instatiaton is less confusing and verbose

2023-03-08 10:47 UTC, Pablito2020 approved these changes

2023-03-08 10:47 UTC, merged